//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.24 at 10:55:39 AM BST 
//


package info.psidev.psi.pi.mzquantml._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Root element of the instance document.
 * 
 * <p>Java class for MzQuantMLType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MzQuantMLType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CvList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}CvListType"/>
 *         &lt;element name="Provider" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}ProviderType" minOccurs="0"/>
 *         &lt;element name="AuditCollection" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}AuditCollectionType" minOccurs="0"/>
 *         &lt;element name="AnalysisSummary" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}ParamListType" minOccurs="0"/>
 *         &lt;element name="InputFiles" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}InputFilesType"/>
 *         &lt;element name="SoftwareList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}SoftwareListType"/>
 *         &lt;element name="DataProcessingList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}DataProcessingListType"/>
 *         &lt;element name="BibliographicReference" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}BibliographicReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AssayList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}AssayListType"/>
 *         &lt;element name="StudyVariableList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}StudyVariableListType"/>
 *         &lt;element name="RatioList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}RatioListType" minOccurs="0"/>
 *         &lt;element name="ProteinGroupList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}ProteinGroupListType" minOccurs="0"/>
 *         &lt;element name="ProteinList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}ProteinListType" minOccurs="0"/>
 *         &lt;element name="PeptideConsensusList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}PeptideConsensusListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SmallMoleculeList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}SmallMoleculeListType" minOccurs="0"/>
 *         &lt;element name="FeatureList" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}FeatureListType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="version" use="required" type="{http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2}versionRegex" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MzQuantMLType", propOrder = {
    "cvList",
    "provider",
    "auditCollection",
    "analysisSummary",
    "inputFiles",
    "softwareList",
    "dataProcessingList",
    "bibliographicReference",
    "assayList",
    "studyVariableList",
    "ratioList",
    "proteinGroupList",
    "proteinList",
    "peptideConsensusList",
    "smallMoleculeList",
    "featureList"
})
@XmlRootElement(name="MzQuantML")
public class MzQuantMLType {

    @XmlElement(name = "CvList", required = true)
    protected CvListType cvList;
    @XmlElement(name = "Provider")
    protected ProviderType provider;
    @XmlElement(name = "AuditCollection")
    protected AuditCollectionType auditCollection;
    @XmlElement(name = "AnalysisSummary")
    protected ParamListType analysisSummary;
    @XmlElement(name = "InputFiles", required = true)
    protected InputFilesType inputFiles;
    @XmlElement(name = "SoftwareList", required = true)
    protected SoftwareListType softwareList;
    @XmlElement(name = "DataProcessingList", required = true)
    protected DataProcessingListType dataProcessingList;
    @XmlElement(name = "BibliographicReference")
    protected List<BibliographicReferenceType> bibliographicReference;
    @XmlElement(name = "AssayList", required = true)
    protected AssayListType assayList;
    @XmlElement(name = "StudyVariableList", required = true)
    protected StudyVariableListType studyVariableList;
    @XmlElement(name = "RatioList")
    protected RatioListType ratioList;
    @XmlElement(name = "ProteinGroupList")
    protected ProteinGroupListType proteinGroupList;
    @XmlElement(name = "ProteinList")
    protected ProteinListType proteinList;
    @XmlElement(name = "PeptideConsensusList")
    protected List<PeptideConsensusListType> peptideConsensusList;
    @XmlElement(name = "SmallMoleculeList")
    protected SmallMoleculeListType smallMoleculeList;
    @XmlElement(name = "FeatureList")
    protected List<FeatureListType> featureList;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the cvList property.
     * 
     * @return
     *     possible object is
     *     {@link CvListType }
     *     
     */
    public CvListType getCvList() {
        return cvList;
    }

    /**
     * Sets the value of the cvList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvListType }
     *     
     */
    public void setCvList(CvListType value) {
        this.cvList = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderType }
     *     
     */
    public ProviderType getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderType }
     *     
     */
    public void setProvider(ProviderType value) {
        this.provider = value;
    }

    /**
     * Gets the value of the auditCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AuditCollectionType }
     *     
     */
    public AuditCollectionType getAuditCollection() {
        return auditCollection;
    }

    /**
     * Sets the value of the auditCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditCollectionType }
     *     
     */
    public void setAuditCollection(AuditCollectionType value) {
        this.auditCollection = value;
    }

    /**
     * Gets the value of the analysisSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ParamListType }
     *     
     */
    public ParamListType getAnalysisSummary() {
        return analysisSummary;
    }

    /**
     * Sets the value of the analysisSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamListType }
     *     
     */
    public void setAnalysisSummary(ParamListType value) {
        this.analysisSummary = value;
    }

    /**
     * Gets the value of the inputFiles property.
     * 
     * @return
     *     possible object is
     *     {@link InputFilesType }
     *     
     */
    public InputFilesType getInputFiles() {
        return inputFiles;
    }

    /**
     * Sets the value of the inputFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputFilesType }
     *     
     */
    public void setInputFiles(InputFilesType value) {
        this.inputFiles = value;
    }

    /**
     * Gets the value of the softwareList property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareListType }
     *     
     */
    public SoftwareListType getSoftwareList() {
        return softwareList;
    }

    /**
     * Sets the value of the softwareList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareListType }
     *     
     */
    public void setSoftwareList(SoftwareListType value) {
        this.softwareList = value;
    }

    /**
     * Gets the value of the dataProcessingList property.
     * 
     * @return
     *     possible object is
     *     {@link DataProcessingListType }
     *     
     */
    public DataProcessingListType getDataProcessingList() {
        return dataProcessingList;
    }

    /**
     * Sets the value of the dataProcessingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProcessingListType }
     *     
     */
    public void setDataProcessingList(DataProcessingListType value) {
        this.dataProcessingList = value;
    }

    /**
     * Gets the value of the bibliographicReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibliographicReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibliographicReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BibliographicReferenceType }
     * 
     * 
     */
    public List<BibliographicReferenceType> getBibliographicReference() {
        if (bibliographicReference == null) {
            bibliographicReference = new ArrayList<BibliographicReferenceType>();
        }
        return this.bibliographicReference;
    }

    /**
     * Gets the value of the assayList property.
     * 
     * @return
     *     possible object is
     *     {@link AssayListType }
     *     
     */
    public AssayListType getAssayList() {
        return assayList;
    }

    /**
     * Sets the value of the assayList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssayListType }
     *     
     */
    public void setAssayList(AssayListType value) {
        this.assayList = value;
    }

    /**
     * Gets the value of the studyVariableList property.
     * 
     * @return
     *     possible object is
     *     {@link StudyVariableListType }
     *     
     */
    public StudyVariableListType getStudyVariableList() {
        return studyVariableList;
    }

    /**
     * Sets the value of the studyVariableList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyVariableListType }
     *     
     */
    public void setStudyVariableList(StudyVariableListType value) {
        this.studyVariableList = value;
    }

    /**
     * Gets the value of the ratioList property.
     * 
     * @return
     *     possible object is
     *     {@link RatioListType }
     *     
     */
    public RatioListType getRatioList() {
        return ratioList;
    }

    /**
     * Sets the value of the ratioList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatioListType }
     *     
     */
    public void setRatioList(RatioListType value) {
        this.ratioList = value;
    }

    /**
     * Gets the value of the proteinGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinGroupListType }
     *     
     */
    public ProteinGroupListType getProteinGroupList() {
        return proteinGroupList;
    }

    /**
     * Sets the value of the proteinGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinGroupListType }
     *     
     */
    public void setProteinGroupList(ProteinGroupListType value) {
        this.proteinGroupList = value;
    }

    /**
     * Gets the value of the proteinList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinListType }
     *     
     */
    public ProteinListType getProteinList() {
        return proteinList;
    }

    /**
     * Sets the value of the proteinList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinListType }
     *     
     */
    public void setProteinList(ProteinListType value) {
        this.proteinList = value;
    }

    /**
     * Gets the value of the peptideConsensusList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the peptideConsensusList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeptideConsensusList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeptideConsensusListType }
     * 
     * 
     */
    public List<PeptideConsensusListType> getPeptideConsensusList() {
        if (peptideConsensusList == null) {
            peptideConsensusList = new ArrayList<PeptideConsensusListType>();
        }
        return this.peptideConsensusList;
    }

    /**
     * Gets the value of the smallMoleculeList property.
     * 
     * @return
     *     possible object is
     *     {@link SmallMoleculeListType }
     *     
     */
    public SmallMoleculeListType getSmallMoleculeList() {
        return smallMoleculeList;
    }

    /**
     * Sets the value of the smallMoleculeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmallMoleculeListType }
     *     
     */
    public void setSmallMoleculeList(SmallMoleculeListType value) {
        this.smallMoleculeList = value;
    }

    /**
     * Gets the value of the featureList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureListType }
     * 
     * 
     */
    public List<FeatureListType> getFeatureList() {
        if (featureList == null) {
            featureList = new ArrayList<FeatureListType>();
        }
        return this.featureList;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
