//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 02:28:44 PM BST 
//


package info.psidev.psi.pi.mzquantml._1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.psidev.psi.pi.mzquantml._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MzQuantML_QNAME = new QName("http://psidev.info/psi/pi/mzQuantML/1.0.0-rc1", "MzQuantML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.psidev.psi.pi.mzquantml._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DBIdentificationRefType }
     * 
     */
    public DBIdentificationRefType createDBIdentificationRefType() {
        return new DBIdentificationRefType();
    }

    /**
     * Create an instance of {@link StudyVariableType }
     * 
     */
    public StudyVariableType createStudyVariableType() {
        return new StudyVariableType();
    }

    /**
     * Create an instance of {@link SearchDatabaseType }
     * 
     */
    public SearchDatabaseType createSearchDatabaseType() {
        return new SearchDatabaseType();
    }

    /**
     * Create an instance of {@link SmallMoleculeType }
     * 
     */
    public SmallMoleculeType createSmallMoleculeType() {
        return new SmallMoleculeType();
    }

    /**
     * Create an instance of {@link ModParamType }
     * 
     */
    public ModParamType createModParamType() {
        return new ModParamType();
    }

    /**
     * Create an instance of {@link InputFilesType }
     * 
     */
    public InputFilesType createInputFilesType() {
        return new InputFilesType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link ParentOrganizationType }
     * 
     */
    public ParentOrganizationType createParentOrganizationType() {
        return new ParentOrganizationType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link DataProcessingListType }
     * 
     */
    public DataProcessingListType createDataProcessingListType() {
        return new DataProcessingListType();
    }

    /**
     * Create an instance of {@link DataProcessingType }
     * 
     */
    public DataProcessingType createDataProcessingType() {
        return new DataProcessingType();
    }

    /**
     * Create an instance of {@link ColumnDefinitionType }
     * 
     */
    public ColumnDefinitionType createColumnDefinitionType() {
        return new ColumnDefinitionType();
    }

    /**
     * Create an instance of {@link IdentificationRefType }
     * 
     */
    public IdentificationRefType createIdentificationRefType() {
        return new IdentificationRefType();
    }

    /**
     * Create an instance of {@link RawFilesGroupType }
     * 
     */
    public RawFilesGroupType createRawFilesGroupType() {
        return new RawFilesGroupType();
    }

    /**
     * Create an instance of {@link AffiliationType }
     * 
     */
    public AffiliationType createAffiliationType() {
        return new AffiliationType();
    }

    /**
     * Create an instance of {@link CvListType }
     * 
     */
    public CvListType createCvListType() {
        return new CvListType();
    }

    /**
     * Create an instance of {@link ExternalDataType }
     * 
     */
    public ExternalDataType createExternalDataType() {
        return new ExternalDataType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link PeptideConsensusType }
     * 
     */
    public PeptideConsensusType createPeptideConsensusType() {
        return new PeptideConsensusType();
    }

    /**
     * Create an instance of {@link SmallMoleculeListType }
     * 
     */
    public SmallMoleculeListType createSmallMoleculeListType() {
        return new SmallMoleculeListType();
    }

    /**
     * Create an instance of {@link AuditCollectionType }
     * 
     */
    public AuditCollectionType createAuditCollectionType() {
        return new AuditCollectionType();
    }

    /**
     * Create an instance of {@link ProteinGroupType }
     * 
     */
    public ProteinGroupType createProteinGroupType() {
        return new ProteinGroupType();
    }

    /**
     * Create an instance of {@link DataMatrixType }
     * 
     */
    public DataMatrixType createDataMatrixType() {
        return new DataMatrixType();
    }

    /**
     * Create an instance of {@link FileFormatType }
     * 
     */
    public FileFormatType createFileFormatType() {
        return new FileFormatType();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link SoftwareListType }
     * 
     */
    public SoftwareListType createSoftwareListType() {
        return new SoftwareListType();
    }

    /**
     * Create an instance of {@link ProcessingMethodType }
     * 
     */
    public ProcessingMethodType createProcessingMethodType() {
        return new ProcessingMethodType();
    }

    /**
     * Create an instance of {@link IdentificationFileType }
     * 
     */
    public IdentificationFileType createIdentificationFileType() {
        return new IdentificationFileType();
    }

    /**
     * Create an instance of {@link StudyVariableListType }
     * 
     */
    public StudyVariableListType createStudyVariableListType() {
        return new StudyVariableListType();
    }

    /**
     * Create an instance of {@link ProteinType }
     * 
     */
    public ProteinType createProteinType() {
        return new ProteinType();
    }

    /**
     * Create an instance of {@link RowType }
     * 
     */
    public RowType createRowType() {
        return new RowType();
    }

    /**
     * Create an instance of {@link FeatureListType }
     * 
     */
    public FeatureListType createFeatureListType() {
        return new FeatureListType();
    }

    /**
     * Create an instance of {@link ProteinGroupListType }
     * 
     */
    public ProteinGroupListType createProteinGroupListType() {
        return new ProteinGroupListType();
    }

    /**
     * Create an instance of {@link ParamListType }
     * 
     */
    public ParamListType createParamListType() {
        return new ParamListType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link GlobalQuantLayerType }
     * 
     */
    public GlobalQuantLayerType createGlobalQuantLayerType() {
        return new GlobalQuantLayerType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link QuantLayerType }
     * 
     */
    public QuantLayerType createQuantLayerType() {
        return new QuantLayerType();
    }

    /**
     * Create an instance of {@link RawFileType }
     * 
     */
    public RawFileType createRawFileType() {
        return new RawFileType();
    }

    /**
     * Create an instance of {@link CvParamRefType }
     * 
     */
    public CvParamRefType createCvParamRefType() {
        return new CvParamRefType();
    }

    /**
     * Create an instance of {@link ModificationType }
     * 
     */
    public ModificationType createModificationType() {
        return new ModificationType();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link AnalysisSummaryType }
     * 
     */
    public AnalysisSummaryType createAnalysisSummaryType() {
        return new AnalysisSummaryType();
    }

    /**
     * Create an instance of {@link IdentificationFilesType }
     * 
     */
    public IdentificationFilesType createIdentificationFilesType() {
        return new IdentificationFilesType();
    }

    /**
     * Create an instance of {@link SmallMolModificationType }
     * 
     */
    public SmallMolModificationType createSmallMolModificationType() {
        return new SmallMolModificationType();
    }

    /**
     * Create an instance of {@link ProteinListType }
     * 
     */
    public ProteinListType createProteinListType() {
        return new ProteinListType();
    }

    /**
     * Create an instance of {@link AssayType }
     * 
     */
    public AssayType createAssayType() {
        return new AssayType();
    }

    /**
     * Create an instance of {@link CVParamType }
     * 
     */
    public CVParamType createCVParamType() {
        return new CVParamType();
    }

    /**
     * Create an instance of {@link RatioType }
     * 
     */
    public RatioType createRatioType() {
        return new RatioType();
    }

    /**
     * Create an instance of {@link AssayListType }
     * 
     */
    public AssayListType createAssayListType() {
        return new AssayListType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link RatioListType }
     * 
     */
    public RatioListType createRatioListType() {
        return new RatioListType();
    }

    /**
     * Create an instance of {@link MzQuantMLType }
     * 
     */
    public MzQuantMLType createMzQuantMLType() {
        return new MzQuantMLType();
    }

    /**
     * Create an instance of {@link ContactRoleType }
     * 
     */
    public ContactRoleType createContactRoleType() {
        return new ContactRoleType();
    }

    /**
     * Create an instance of {@link BibliographicReferenceType }
     * 
     */
    public BibliographicReferenceType createBibliographicReferenceType() {
        return new BibliographicReferenceType();
    }

    /**
     * Create an instance of {@link PeptideConsensusListType }
     * 
     */
    public PeptideConsensusListType createPeptideConsensusListType() {
        return new PeptideConsensusListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MzQuantMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psidev.info/psi/pi/mzQuantML/1.0.0-rc1", name = "MzQuantML")
    public JAXBElement<MzQuantMLType> createMzQuantML(MzQuantMLType value) {
        return new JAXBElement<MzQuantMLType>(_MzQuantML_QNAME, MzQuantMLType.class, null, value);
    }

}
