//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 10:54:59 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.psidev.psi.pi.mzquantml._1_0;
