//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.16 at 01:42:41 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzQuantML/1.0.0-rc1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.mpc.MzQuantMLWrapper;
