//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.26 at 01:45:50 PM BST 
//


package info.psidev.psi.pi.mzquantml._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cvList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}cvListType"/>
 *         &lt;element name="InputFiles" type="{http://psidev.info/psi/pi/mzQuantML/0.1}InputFilesType"/>
 *         &lt;element name="AssayList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}AssayListType"/>
 *         &lt;element name="StudyVariableList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}StudyVariableListType"/>
 *         &lt;element name="RatioList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}RatioListType" minOccurs="0"/>
 *         &lt;element name="ProteinGroupList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}ProteinGroupListType" minOccurs="0"/>
 *         &lt;element name="ProteinList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}ProteinListType" minOccurs="0"/>
 *         &lt;element name="PeptideList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}PeptideListType" minOccurs="0"/>
 *         &lt;element name="FeatureList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}FeatureListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MatchedFeatureList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}MatchedFeatureListType" minOccurs="0"/>
 *         &lt;element name="DataProcessingList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}DataProcessingListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cvList",
    "inputFiles",
    "assayList",
    "studyVariableList",
    "ratioList",
    "proteinGroupList",
    "proteinList",
    "peptideList",
    "featureList",
    "matchedFeatureList",
    "dataProcessingList"
})
@XmlRootElement(name = "mzQuantML")
public class MzQuantML {

    @XmlElement(required = true)
    protected CvListType cvList;
    @XmlElement(name = "InputFiles", required = true)
    protected InputFilesType inputFiles;
    @XmlElement(name = "AssayList", required = true)
    protected AssayListType assayList;
    @XmlElement(name = "StudyVariableList", required = true)
    protected StudyVariableListType studyVariableList;
    @XmlElement(name = "RatioList")
    protected RatioListType ratioList;
    @XmlElement(name = "ProteinGroupList")
    protected ProteinGroupListType proteinGroupList;
    @XmlElement(name = "ProteinList")
    protected ProteinListType proteinList;
    @XmlElement(name = "PeptideList")
    protected PeptideListType peptideList;
    @XmlElement(name = "FeatureList")
    protected List<FeatureListType> featureList;
    @XmlElement(name = "MatchedFeatureList")
    protected MatchedFeatureListType matchedFeatureList;
    @XmlElement(name = "DataProcessingList")
    protected DataProcessingListType dataProcessingList;

    /**
     * Gets the value of the cvList property.
     * 
     * @return
     *     possible object is
     *     {@link CvListType }
     *     
     */
    public CvListType getCvList() {
        return cvList;
    }

    /**
     * Sets the value of the cvList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvListType }
     *     
     */
    public void setCvList(CvListType value) {
        this.cvList = value;
    }

    /**
     * Gets the value of the inputFiles property.
     * 
     * @return
     *     possible object is
     *     {@link InputFilesType }
     *     
     */
    public InputFilesType getInputFiles() {
        return inputFiles;
    }

    /**
     * Sets the value of the inputFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputFilesType }
     *     
     */
    public void setInputFiles(InputFilesType value) {
        this.inputFiles = value;
    }

    /**
     * Gets the value of the assayList property.
     * 
     * @return
     *     possible object is
     *     {@link AssayListType }
     *     
     */
    public AssayListType getAssayList() {
        return assayList;
    }

    /**
     * Sets the value of the assayList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssayListType }
     *     
     */
    public void setAssayList(AssayListType value) {
        this.assayList = value;
    }

    /**
     * Gets the value of the studyVariableList property.
     * 
     * @return
     *     possible object is
     *     {@link StudyVariableListType }
     *     
     */
    public StudyVariableListType getStudyVariableList() {
        return studyVariableList;
    }

    /**
     * Sets the value of the studyVariableList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyVariableListType }
     *     
     */
    public void setStudyVariableList(StudyVariableListType value) {
        this.studyVariableList = value;
    }

    /**
     * Gets the value of the ratioList property.
     * 
     * @return
     *     possible object is
     *     {@link RatioListType }
     *     
     */
    public RatioListType getRatioList() {
        return ratioList;
    }

    /**
     * Sets the value of the ratioList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatioListType }
     *     
     */
    public void setRatioList(RatioListType value) {
        this.ratioList = value;
    }

    /**
     * Gets the value of the proteinGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinGroupListType }
     *     
     */
    public ProteinGroupListType getProteinGroupList() {
        return proteinGroupList;
    }

    /**
     * Sets the value of the proteinGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinGroupListType }
     *     
     */
    public void setProteinGroupList(ProteinGroupListType value) {
        this.proteinGroupList = value;
    }

    /**
     * Gets the value of the proteinList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinListType }
     *     
     */
    public ProteinListType getProteinList() {
        return proteinList;
    }

    /**
     * Sets the value of the proteinList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinListType }
     *     
     */
    public void setProteinList(ProteinListType value) {
        this.proteinList = value;
    }

    /**
     * Gets the value of the peptideList property.
     * 
     * @return
     *     possible object is
     *     {@link PeptideListType }
     *     
     */
    public PeptideListType getPeptideList() {
        return peptideList;
    }

    /**
     * Sets the value of the peptideList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeptideListType }
     *     
     */
    public void setPeptideList(PeptideListType value) {
        this.peptideList = value;
    }

    /**
     * Gets the value of the featureList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureListType }
     * 
     * 
     */
    public List<FeatureListType> getFeatureList() {
        if (featureList == null) {
            featureList = new ArrayList<FeatureListType>();
        }
        return this.featureList;
    }

    /**
     * Gets the value of the matchedFeatureList property.
     * 
     * @return
     *     possible object is
     *     {@link MatchedFeatureListType }
     *     
     */
    public MatchedFeatureListType getMatchedFeatureList() {
        return matchedFeatureList;
    }

    /**
     * Sets the value of the matchedFeatureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedFeatureListType }
     *     
     */
    public void setMatchedFeatureList(MatchedFeatureListType value) {
        this.matchedFeatureList = value;
    }

    /**
     * Gets the value of the dataProcessingList property.
     * 
     * @return
     *     possible object is
     *     {@link DataProcessingListType }
     *     
     */
    public DataProcessingListType getDataProcessingList() {
        return dataProcessingList;
    }

    /**
     * Sets the value of the dataProcessingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProcessingListType }
     *     
     */
    public void setDataProcessingList(DataProcessingListType value) {
        this.dataProcessingList = value;
    }

}
