//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.16 at 11:33:56 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.psidev.psi.pi.mzquantml._1_0;
