//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 05:05:23 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzQuantML/1.0.0-rc2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.psidev.psi.pi.mzquantml._1_0;
