//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 02:00:54 PM BST 
//


package info.psidev.psi.pi.mzquantml._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An optional element for inserting references from a particular cell of the data matrix in this QuantLayer to positions in other QuantLayers. Note - the use of this element for data export is not generally recommended since it will hugely increase file sizes
 * 
 * <p>Java class for CellSourceRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CellSourceRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QLCellRef" type="{http://psidev.info/psi/pi/mzQuantML/0.1}QLCellRefType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="col" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="row" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CellSourceRefType", propOrder = {
    "qlCellRef"
})
public class CellSourceRefType {

    @XmlElement(name = "QLCellRef", required = true)
    protected List<QLCellRefType> qlCellRef;
    @XmlAttribute(required = true)
    protected int col;
    @XmlAttribute(required = true)
    protected int row;

    /**
     * Gets the value of the qlCellRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qlCellRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQLCellRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QLCellRefType }
     * 
     * 
     */
    public List<QLCellRefType> getQLCellRef() {
        if (qlCellRef == null) {
            qlCellRef = new ArrayList<QLCellRefType>();
        }
        return this.qlCellRef;
    }

    /**
     * Gets the value of the col property.
     * 
     */
    public int getCol() {
        return col;
    }

    /**
     * Sets the value of the col property.
     * 
     */
    public void setCol(int value) {
        this.col = value;
    }

    /**
     * Gets the value of the row property.
     * 
     */
    public int getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     */
    public void setRow(int value) {
        this.row = value;
    }

}
