//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 02:00:54 PM BST 
//


package info.psidev.psi.pi.mzquantml._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cvList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}cvListType"/>
 *         &lt;element name="AssayList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}AssayListType"/>
 *         &lt;element name="StudyVariableList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}StudyVariableListType"/>
 *         &lt;element name="ProteinGroupList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}ProteinGroupListType" minOccurs="0"/>
 *         &lt;element name="ProteinList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}ProteinListType" minOccurs="0"/>
 *         &lt;element name="PeptideList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}PeptideListType" minOccurs="0"/>
 *         &lt;element name="FeatureList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}FeatureListType" minOccurs="0"/>
 *         &lt;element name="MatchedFeatureList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}MatchedFeatureListType"/>
 *         &lt;element name="QuantLayerList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}QuantLayerListType" minOccurs="0"/>
 *         &lt;element name="DataProcessingList" type="{http://psidev.info/psi/pi/mzQuantML/0.1}DataProcessingListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cvList",
    "assayList",
    "studyVariableList",
    "proteinGroupList",
    "proteinList",
    "peptideList",
    "featureList",
    "matchedFeatureList",
    "quantLayerList",
    "dataProcessingList"
})
@XmlRootElement(name = "mzQuantML")
public class MzQuantML {

    @XmlElement(required = true)
    protected CvListType cvList;
    @XmlElement(name = "AssayList", required = true)
    protected AssayListType assayList;
    @XmlElement(name = "StudyVariableList", required = true)
    protected StudyVariableListType studyVariableList;
    @XmlElement(name = "ProteinGroupList")
    protected ProteinGroupListType proteinGroupList;
    @XmlElement(name = "ProteinList")
    protected ProteinListType proteinList;
    @XmlElement(name = "PeptideList")
    protected PeptideListType peptideList;
    @XmlElement(name = "FeatureList")
    protected FeatureListType featureList;
    @XmlElement(name = "MatchedFeatureList", required = true)
    protected MatchedFeatureListType matchedFeatureList;
    @XmlElement(name = "QuantLayerList")
    protected QuantLayerListType quantLayerList;
    @XmlElement(name = "DataProcessingList")
    protected DataProcessingListType dataProcessingList;

    /**
     * Gets the value of the cvList property.
     * 
     * @return
     *     possible object is
     *     {@link CvListType }
     *     
     */
    public CvListType getCvList() {
        return cvList;
    }

    /**
     * Sets the value of the cvList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvListType }
     *     
     */
    public void setCvList(CvListType value) {
        this.cvList = value;
    }

    /**
     * Gets the value of the assayList property.
     * 
     * @return
     *     possible object is
     *     {@link AssayListType }
     *     
     */
    public AssayListType getAssayList() {
        return assayList;
    }

    /**
     * Sets the value of the assayList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssayListType }
     *     
     */
    public void setAssayList(AssayListType value) {
        this.assayList = value;
    }

    /**
     * Gets the value of the studyVariableList property.
     * 
     * @return
     *     possible object is
     *     {@link StudyVariableListType }
     *     
     */
    public StudyVariableListType getStudyVariableList() {
        return studyVariableList;
    }

    /**
     * Sets the value of the studyVariableList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyVariableListType }
     *     
     */
    public void setStudyVariableList(StudyVariableListType value) {
        this.studyVariableList = value;
    }

    /**
     * Gets the value of the proteinGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinGroupListType }
     *     
     */
    public ProteinGroupListType getProteinGroupList() {
        return proteinGroupList;
    }

    /**
     * Sets the value of the proteinGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinGroupListType }
     *     
     */
    public void setProteinGroupList(ProteinGroupListType value) {
        this.proteinGroupList = value;
    }

    /**
     * Gets the value of the proteinList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinListType }
     *     
     */
    public ProteinListType getProteinList() {
        return proteinList;
    }

    /**
     * Sets the value of the proteinList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinListType }
     *     
     */
    public void setProteinList(ProteinListType value) {
        this.proteinList = value;
    }

    /**
     * Gets the value of the peptideList property.
     * 
     * @return
     *     possible object is
     *     {@link PeptideListType }
     *     
     */
    public PeptideListType getPeptideList() {
        return peptideList;
    }

    /**
     * Sets the value of the peptideList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeptideListType }
     *     
     */
    public void setPeptideList(PeptideListType value) {
        this.peptideList = value;
    }

    /**
     * Gets the value of the featureList property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureListType }
     *     
     */
    public FeatureListType getFeatureList() {
        return featureList;
    }

    /**
     * Sets the value of the featureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureListType }
     *     
     */
    public void setFeatureList(FeatureListType value) {
        this.featureList = value;
    }

    /**
     * Gets the value of the matchedFeatureList property.
     * 
     * @return
     *     possible object is
     *     {@link MatchedFeatureListType }
     *     
     */
    public MatchedFeatureListType getMatchedFeatureList() {
        return matchedFeatureList;
    }

    /**
     * Sets the value of the matchedFeatureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedFeatureListType }
     *     
     */
    public void setMatchedFeatureList(MatchedFeatureListType value) {
        this.matchedFeatureList = value;
    }

    /**
     * Gets the value of the quantLayerList property.
     * 
     * @return
     *     possible object is
     *     {@link QuantLayerListType }
     *     
     */
    public QuantLayerListType getQuantLayerList() {
        return quantLayerList;
    }

    /**
     * Sets the value of the quantLayerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantLayerListType }
     *     
     */
    public void setQuantLayerList(QuantLayerListType value) {
        this.quantLayerList = value;
    }

    /**
     * Gets the value of the dataProcessingList property.
     * 
     * @return
     *     possible object is
     *     {@link DataProcessingListType }
     *     
     */
    public DataProcessingListType getDataProcessingList() {
        return dataProcessingList;
    }

    /**
     * Sets the value of the dataProcessingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProcessingListType }
     *     
     */
    public void setDataProcessingList(DataProcessingListType value) {
        this.dataProcessingList = value;
    }

}
