//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.28 at 03:44:34 PM BST 
//


package info.psidev.psi.pi.mzquantml._0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the info.psidev.psi.pi.mzquantml._0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

private final static QName _MzQuantML_QNAME = new QName("http://psidev.info/psi/pi/mzIdentML/1.1", "MzQuantML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: info.psidev.psi.pi.mzquantml._0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FeatureListType }
     * 
     */
    public FeatureListType createFeatureListType() {
        return new FeatureListType();
    }

    /**
     * Create an instance of {@link MatchedFeatureListType }
     * 
     */
    public MatchedFeatureListType createMatchedFeatureListType() {
        return new MatchedFeatureListType();
    }

    /**
     * Create an instance of {@link DataProcessingListType }
     * 
     */
    public DataProcessingListType createDataProcessingListType() {
        return new DataProcessingListType();
    }

    /**
     * Create an instance of {@link RawFilesType.RawFile }
     * 
     */
    public RawFilesType.RawFile createRawFilesTypeRawFile() {
        return new RawFilesType.RawFile();
    }

    /**
     * Create an instance of {@link StudyVariableRefsType.StudyVariableRef }
     * 
     */
    public StudyVariableRefsType.StudyVariableRef createStudyVariableRefsTypeStudyVariableRef() {
        return new StudyVariableRefsType.StudyVariableRef();
    }

    /**
     * Create an instance of {@link QuantLayerRefType }
     * 
     */
    public QuantLayerRefType createQuantLayerRefType() {
        return new QuantLayerRefType();
    }

    /**
     * Create an instance of {@link SpectraSetType.SpectrumIdentificationItemRef }
     * 
     */
    public SpectraSetType.SpectrumIdentificationItemRef createSpectraSetTypeSpectrumIdentificationItemRef() {
        return new SpectraSetType.SpectrumIdentificationItemRef();
    }

    /**
     * Create an instance of {@link DataMatrixType }
     * 
     */
    public DataMatrixType createDataMatrixType() {
        return new DataMatrixType();
    }

    /**
     * Create an instance of {@link ParamListType }
     * 
     */
    public ParamListType createParamListType() {
        return new ParamListType();
    }

    /**
     * Create an instance of {@link FeatureRefsType.FeatureRef }
     * 
     */
    public FeatureRefsType.FeatureRef createFeatureRefsTypeFeatureRef() {
        return new FeatureRefsType.FeatureRef();
    }

    /**
     * Create an instance of {@link ProteinDetectionHypothesisRefsType.ProteinDetectionHypothesisRef }
     * 
     */
    public ProteinDetectionHypothesisRefsType.ProteinDetectionHypothesisRef createProteinDetectionHypothesisRefsTypeProteinDetectionHypothesisRef() {
        return new ProteinDetectionHypothesisRefsType.ProteinDetectionHypothesisRef();
    }

    /**
     * Create an instance of {@link SpectraSetsType }
     * 
     */
    public SpectraSetsType createSpectraSetsType() {
        return new SpectraSetsType();
    }

    /**
     * Create an instance of {@link IdentificationFilesType.IdentificationFile }
     * 
     */
    public IdentificationFilesType.IdentificationFile createIdentificationFilesTypeIdentificationFile() {
        return new IdentificationFilesType.IdentificationFile();
    }

    /**
     * Create an instance of {@link PeptideListType }
     * 
     */
    public PeptideListType createPeptideListType() {
        return new PeptideListType();
    }

    /**
     * Create an instance of {@link CvParamType }
     * 
     */
    public CvParamType createCvParamType() {
        return new CvParamType();
    }

    /**
     * Create an instance of {@link PeptideType }
     * 
     */
    public PeptideType createPeptideType() {
        return new PeptideType();
    }

    /**
     * Create an instance of {@link ProteinListType }
     * 
     */
    public ProteinListType createProteinListType() {
        return new ProteinListType();
    }

    /**
     * Create an instance of {@link SpectraSetType }
     * 
     */
    public SpectraSetType createSpectraSetType() {
        return new SpectraSetType();
    }

    /**
     * Create an instance of {@link AssayType.DataProcessingOrder }
     * 
     */
    public AssayType.DataProcessingOrder createAssayTypeDataProcessingOrder() {
        return new AssayType.DataProcessingOrder();
    }

    /**
     * Create an instance of {@link QLCellRefType }
     * 
     */
    public QLCellRefType createQLCellRefType() {
        return new QLCellRefType();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link RatioType }
     * 
     */
    public RatioType createRatioType() {
        return new RatioType();
    }

    /**
     * Create an instance of {@link CvListType }
     * 
     */
    public CvListType createCvListType() {
        return new CvListType();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link StudyVariableType }
     * 
     */
    public StudyVariableType createStudyVariableType() {
        return new StudyVariableType();
    }

    /**
     * Create an instance of {@link RatioType.Numerator }
     * 
     */
    public RatioType.Numerator createRatioTypeNumerator() {
        return new RatioType.Numerator();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link FeatureRefsType }
     * 
     */
    public FeatureRefsType createFeatureRefsType() {
        return new FeatureRefsType();
    }

    /**
     * Create an instance of {@link RatioType.Denominator }
     * 
     */
    public RatioType.Denominator createRatioTypeDenominator() {
        return new RatioType.Denominator();
    }

    /**
     * Create an instance of {@link ProtocolType }
     * 
     */
    public ProtocolType createProtocolType() {
        return new ProtocolType();
    }

    /**
     * Create an instance of {@link DataMatrixType.Row }
     * 
     */
    public DataMatrixType.Row createDataMatrixTypeRow() {
        return new DataMatrixType.Row();
    }

    /**
     * Create an instance of {@link QuantValueRefsType.QuantValueRef }
     * 
     */
    public QuantValueRefsType.QuantValueRef createQuantValueRefsTypeQuantValueRef() {
        return new QuantValueRefsType.QuantValueRef();
    }

    /**
     * Create an instance of {@link CvParamRefType }
     * 
     */
    public CvParamRefType createCvParamRefType() {
        return new CvParamRefType();
    }

    /**
     * Create an instance of {@link MatchedFeatureType }
     * 
     */
    public MatchedFeatureType createMatchedFeatureType() {
        return new MatchedFeatureType();
    }

    /**
     * Create an instance of {@link IdentificationFilesType }
     * 
     */
    public IdentificationFilesType createIdentificationFilesType() {
        return new IdentificationFilesType();
    }

    /**
     * Create an instance of {@link QuantLayerType }
     * 
     */
    public QuantLayerType createQuantLayerType() {
        return new QuantLayerType();
    }

    /**
     * Create an instance of {@link MzQuantML }
     * 
     */
    public MzQuantML createMzQuantML() {
        return new MzQuantML();
    }

    /**
     * Create an instance of {@link DataProcessingType }
     * 
     */
    public DataProcessingType createDataProcessingType() {
        return new DataProcessingType();
    }

    /**
     * Create an instance of {@link RatioType.Numerator.QuantMeasurementRef }
     * 
     */
    public RatioType.Numerator.QuantMeasurementRef createRatioTypeNumeratorQuantMeasurementRef() {
        return new RatioType.Numerator.QuantMeasurementRef();
    }

    /**
     * Create an instance of {@link QuantValueType }
     * 
     */
    public QuantValueType createQuantValueType() {
        return new QuantValueType();
    }

    /**
     * Create an instance of {@link StudyVariableListType }
     * 
     */
    public StudyVariableListType createStudyVariableListType() {
        return new StudyVariableListType();
    }

    /**
     * Create an instance of {@link PeptideRefsType }
     * 
     */
    public PeptideRefsType createPeptideRefsType() {
        return new PeptideRefsType();
    }

    /**
     * Create an instance of {@link RawFilesType }
     * 
     */
    public RawFilesType createRawFilesType() {
        return new RawFilesType();
    }

    /**
     * Create an instance of {@link ProtocolListType }
     * 
     */
    public ProtocolListType createProtocolListType() {
        return new ProtocolListType();
    }

    /**
     * Create an instance of {@link IdentificationRefType }
     * 
     */
    public IdentificationRefType createIdentificationRefType() {
        return new IdentificationRefType();
    }

    /**
     * Create an instance of {@link CellSourceRefType }
     * 
     */
    public CellSourceRefType createCellSourceRefType() {
        return new CellSourceRefType();
    }

    /**
     * Create an instance of {@link PeptideRefType }
     * 
     */
    public PeptideRefType createPeptideRefType() {
        return new PeptideRefType();
    }

    /**
     * Create an instance of {@link ProteinDetectionHypothesisRefsType }
     * 
     */
    public ProteinDetectionHypothesisRefsType createProteinDetectionHypothesisRefsType() {
        return new ProteinDetectionHypothesisRefsType();
    }

    /**
     * Create an instance of {@link QuantLayerListType }
     * 
     */
    public QuantLayerListType createQuantLayerListType() {
        return new QuantLayerListType();
    }

    /**
     * Create an instance of {@link AssayListType }
     * 
     */
    public AssayListType createAssayListType() {
        return new AssayListType();
    }

    /**
     * Create an instance of {@link AssayType }
     * 
     */
    public AssayType createAssayType() {
        return new AssayType();
    }

    /**
     * Create an instance of {@link ProcessingMethodType }
     * 
     */
    public ProcessingMethodType createProcessingMethodType() {
        return new ProcessingMethodType();
    }

    /**
     * Create an instance of {@link AssayType.DataProcessingOrder.DataProcessingOrderElement }
     * 
     */
    public AssayType.DataProcessingOrder.DataProcessingOrderElement createAssayTypeDataProcessingOrderDataProcessingOrderElement() {
        return new AssayType.DataProcessingOrder.DataProcessingOrderElement();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link ParamGroupType }
     * 
     */
    public ParamGroupType createParamGroupType() {
        return new ParamGroupType();
    }

    /**
     * Create an instance of {@link ProteinGroupType }
     * 
     */
    public ProteinGroupType createProteinGroupType() {
        return new ProteinGroupType();
    }

    /**
     * Create an instance of {@link ProteinType }
     * 
     */
    public ProteinType createProteinType() {
        return new ProteinType();
    }

    /**
     * Create an instance of {@link ModParamType }
     * 
     */
    public ModParamType createModParamType() {
        return new ModParamType();
    }

    /**
     * Create an instance of {@link RatioType.Denominator.QuantMeasurementRef }
     * 
     */
    public RatioType.Denominator.QuantMeasurementRef createRatioTypeDenominatorQuantMeasurementRef() {
        return new RatioType.Denominator.QuantMeasurementRef();
    }

    /**
     * Create an instance of {@link ModificationType }
     * 
     */
    public ModificationType createModificationType() {
        return new ModificationType();
    }

    /**
     * Create an instance of {@link StudyVariableType.AssayRef }
     * 
     */
    public StudyVariableType.AssayRef createStudyVariableTypeAssayRef() {
        return new StudyVariableType.AssayRef();
    }

    /**
     * Create an instance of {@link QuantitationsLayerType }
     * 
     */
    public QuantitationsLayerType createQuantitationsLayerType() {
        return new QuantitationsLayerType();
    }

    /**
     * Create an instance of {@link ProteinGroupListType }
     * 
     */
    public ProteinGroupListType createProteinGroupListType() {
        return new ProteinGroupListType();
    }

    /**
     * Create an instance of {@link QuantValueRefsType }
     * 
     */
    public QuantValueRefsType createQuantValueRefsType() {
        return new QuantValueRefsType();
    }

    /**
     * Create an instance of {@link StudyVariableRefsType }
     * 
     */
    public StudyVariableRefsType createStudyVariableRefsType() {
        return new StudyVariableRefsType();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MzIdentML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mzquantml/0.1.4", name = "MzQuantML")
    public JAXBElement<MzQuantML> createMzQuantML(MzQuantML value) {
        return new JAXBElement<MzQuantML>(_MzQuantML_QNAME, MzQuantML.class, null, value);
    }


}
