//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.26 at 01:45:50 PM BST 
//


package info.psidev.psi.pi.mzquantml._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpectraSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpectraSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpectrumIdentificationItemRef" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="file_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="spectrumIdentificationItem_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpectraSetType", propOrder = {
    "spectrumIdentificationItemRef"
})
public class SpectraSetType {

    @XmlElement(name = "SpectrumIdentificationItemRef", required = true)
    protected List<SpectraSetType.SpectrumIdentificationItemRef> spectrumIdentificationItemRef;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the spectrumIdentificationItemRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spectrumIdentificationItemRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpectrumIdentificationItemRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpectraSetType.SpectrumIdentificationItemRef }
     * 
     * 
     */
    public List<SpectraSetType.SpectrumIdentificationItemRef> getSpectrumIdentificationItemRef() {
        if (spectrumIdentificationItemRef == null) {
            spectrumIdentificationItemRef = new ArrayList<SpectraSetType.SpectrumIdentificationItemRef>();
        }
        return this.spectrumIdentificationItemRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="file_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="spectrumIdentificationItem_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SpectrumIdentificationItemRef {

        @XmlAttribute(name = "file_ref")
        protected String fileRef;
        @XmlAttribute(name = "spectrumIdentificationItem_ref")
        protected String spectrumIdentificationItemRef;

        /**
         * Gets the value of the fileRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileRef() {
            return fileRef;
        }

        /**
         * Sets the value of the fileRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileRef(String value) {
            this.fileRef = value;
        }

        /**
         * Gets the value of the spectrumIdentificationItemRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpectrumIdentificationItemRef() {
            return spectrumIdentificationItemRef;
        }

        /**
         * Sets the value of the spectrumIdentificationItemRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpectrumIdentificationItemRef(String value) {
            this.spectrumIdentificationItemRef = value;
        }

    }

}
